server:
  port: 8100

spring:
  application:
    name: session-management-example
  datasource:
    url: jdbc:h2:mem:sessionmgmt
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  h2:
    console:
      enabled: true
  session:
    timeout: 30m
