package com.cinetrack;

import com.cinetrack.token.TokenResponse;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.resttestclient.TestRestTemplate;
import org.springframework.boot.resttestclient.autoconfigure.AutoConfigureTestRestTemplate;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;

import java.util.Base64;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Integration tests for token issuance via the TokenController.
 *
 * Boots the full application context on a random port and performs real HTTP
 * calls. The JWT returned is signed with the RSAKey generated by JwkConfig : 
 * we validate the claims by decoding the payload manually (Base64URL) rather
 * than verifying the signature, which is covered by JwtValidationTest.
 */
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@AutoConfigureTestRestTemplate
class TokenIssuanceTest {

    @LocalServerPort
    private int port;

    @Autowired
    private TestRestTemplate restTemplate;

    private String baseUrl() {
        return "http://localhost:" + port;
    }

    @Test
    void clientCredentials_returnsJwt() {
        Map<String, String> body = Map.of("clientId", "catalog-service", "scope", "catalog:read");

        ResponseEntity<TokenResponse> response = restTemplate.postForEntity(
                baseUrl() + "/api/token/client-credentials",
                body,
                TokenResponse.class
        );

        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(response.getBody()).isNotNull();
        assertThat(response.getBody().accessToken()).isNotBlank();
        assertThat(response.getBody().tokenType()).isEqualTo("Bearer");
    }

    @Test
    void clientCredentials_jwtContainsScopeClaim() {
        Map<String, String> body = Map.of("clientId", "catalog-service", "scope", "catalog:read");

        ResponseEntity<TokenResponse> response = restTemplate.postForEntity(
                baseUrl() + "/api/token/client-credentials",
                body,
                TokenResponse.class
        );

        assertThat(response.getBody()).isNotNull();
        String jwt = response.getBody().accessToken();
        String payload = decodeJwtPayload(jwt);

        assertThat(payload).contains("\"scope\"");
        assertThat(payload).contains("catalog:read");
    }

    @Test
    void clientCredentials_jwtContainsExpectedAudience() {
        Map<String, String> body = Map.of("clientId", "catalog-service", "scope", "catalog:read");

        ResponseEntity<TokenResponse> response = restTemplate.postForEntity(
                baseUrl() + "/api/token/client-credentials",
                body,
                TokenResponse.class
        );

        assertThat(response.getBody()).isNotNull();
        String jwt = response.getBody().accessToken();
        String payload = decodeJwtPayload(jwt);

        // The audience claim must identify cinetrack-catalog as the intended recipient
        assertThat(payload).contains("cinetrack-catalog");
    }

    @Test
    void authorizationCode_returnsJwtWithUserSubject() {
        Map<String, String> body = Map.of("clientId", "web-app", "scope", "catalog:read profile");

        ResponseEntity<TokenResponse> response = restTemplate.postForEntity(
                baseUrl() + "/api/token/authorization-code",
                body,
                TokenResponse.class
        );

        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(response.getBody()).isNotNull();

        String jwt = response.getBody().accessToken();
        String payload = decodeJwtPayload(jwt);

        // Authorization code flow tokens carry a user subject, not a client subject
        assertThat(payload).contains("user:");
    }

    // ---- helpers --------------------------------------------------------

    /**
     * Decodes the payload section of a JWT without signature verification.
     * Sufficient for asserting on claim values in integration tests where
     * we control the issuer and don't need to re-validate trust.
     */
    private String decodeJwtPayload(String jwt) {
        String[] parts = jwt.split("\\.");
        assertThat(parts).hasSize(3);
        byte[] payloadBytes = Base64.getUrlDecoder().decode(parts[1]);
        return new String(payloadBytes);
    }
}
