server:
  port: 8088

spring:
  application:
    name: api-key-authentication-example
  datasource:
    url: jdbc:h2:mem:apikeydb
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  h2:
    console:
      enabled: true
