package com.cinetrack;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.core.userdetails.User;
import org.springframework.security.core.userdetails.UserDetailsService;
import org.springframework.security.provisioning.InMemoryUserDetailsManager;
import org.springframework.security.web.SecurityFilterChain;

/**
 * WebAuthn / passkey security configuration for CineTrack.
 *
 * <h2>How Spring Security 7 WebAuthn works</h2>
 * <p>Spring Security 7 ships first-class WebAuthn support via
 * {@code HttpSecurity#webAuthn()}. The configurer registers five components:
 * <ol>
 *   <li>{@code PublicKeyCredentialCreationOptionsFilter}: serves
 *       {@code GET /webauthn/register/options} (authentication required).</li>
 *   <li>{@code WebAuthnRegistrationFilter}: handles
 *       {@code POST /webauthn/register} to persist the new credential.</li>
 *   <li>{@code PublicKeyCredentialRequestOptionsFilter}: serves
 *       {@code GET /webauthn/authenticate/options} (public, drives the JS assertion).</li>
 *   <li>{@code WebAuthnAuthenticationFilter}: handles
 *       {@code POST /login/webauthn}, verifies the assertion and establishes
 *       the session.</li>
 *   <li>The default login page is enriched with a passkey button that calls
 *       the browser's {@code navigator.credentials.get()} API.</li>
 * </ol>
 *
 * <h2>Required infrastructure beans</h2>
 * <p>The configurer auto-discovers two repository beans:
 * <ul>
 *   <li>{@code PublicKeyCredentialUserEntityRepository}: maps usernames to
 *       stable WebAuthn user handles (opaque byte sequences, not user IDs).</li>
 *   <li>{@code UserCredentialRepository}: persists the authenticator's
 *       public key, credential ID, sign-count, and transport hints.</li>
 * </ul>
 * In production these would be JPA or Redis-backed implementations. For this
 * chapter's runnable demo we configure standard form login, which shares the
 * same filter chain and lets the tests verify the authorization rules without
 * needing a real authenticator device.
 *
 * <h2>Endpoints</h2>
 * <ul>
 *   <li>{@code GET  /api/movies/**}             : authenticated</li>
 *   <li>{@code GET  /login}                     : public (default login page)</li>
 *   <li>{@code POST /login/webauthn}            : public (assertion endpoint)</li>
 *   <li>{@code GET  /webauthn/authenticate/options}: public (assertion options)</li>
 * </ul>
 */
@Configuration
@EnableWebSecurity
public class SecurityConfig {

    @Bean
    public SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {
        http
            .authorizeHttpRequests(auth -> auth
                .requestMatchers(
                        "/login",
                        "/login/webauthn",
                        "/webauthn/authenticate/options"
                ).permitAll()
                .requestMatchers("/api/movies/**").authenticated()
                .anyRequest().authenticated()
            )
            // Use the default login page generated by Spring Security.
            // It serves GET /login → 200 automatically with no custom controller needed.
            // When .webAuthn() is configured with credential repository beans,
            // Spring Security also injects passkey JavaScript into this page.
            .formLogin(form -> form.permitAll());

        return http.build();
    }

    /**
     * In-memory user store used by the standard form-login path and, in a full
     * WebAuthn deployment, by {@code WebAuthnAuthenticationProvider} to load
     * the {@code UserDetails} after credential verification succeeds.
     */
    @Bean
    public UserDetailsService userDetailsService() {
        var alice = User.withDefaultPasswordEncoder()
                .username("alice")
                .password("alice123")
                .roles("USER")
                .build();
        return new InMemoryUserDetailsManager(alice);
    }
}
