server:
  port: 8090

spring:
  application:
    name: multi-factor-auth-example
  datasource:
    url: jdbc:h2:mem:mfadb
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  h2:
    console:
      enabled: true
