package com.cinetrack;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;
import org.springframework.web.context.WebApplicationContext;

import static org.hamcrest.Matchers.containsString;
import static org.springframework.security.test.web.servlet.setup.SecurityMockMvcConfigurers.springSecurity;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.content;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

/**
 * Verifies that the default login page generated by Spring Security includes
 * a login form that the passkey JavaScript bridge can attach to.
 *
 * <p>Spring Security 7 generates a default login page at {@code GET /login}
 * when {@code .formLogin()} is configured. When {@code .webAuthn()} is
 * additionally wired with credential repository beans, the page also includes
 * a {@code <script>} block that calls {@code navigator.credentials.get()} via
 * the {@code /login/webauthn} assertion endpoint.
 *
 * <p>This test verifies the foundation — a 200 response with an HTML body
 * containing a login form — confirming the security chain is correctly wired.
 */
@SpringBootTest
class PasskeyLoginPageTest {

    @Autowired
    WebApplicationContext context;

    MockMvc mockMvc;

    @BeforeEach
    void setUp() {
        mockMvc = MockMvcBuilders
                .webAppContextSetup(context)
                .apply(springSecurity())
                .build();
    }

    @Test
    @DisplayName("GET /login → 200 and page contains a login form")
    void loginPage_isAccessibleAndContainsForm() throws Exception {
        mockMvc.perform(get("/login"))
                .andExpect(status().isOk())
                .andExpect(content().string(containsString("form")));
    }
}
