server:
  port: 8087

spring:
  application:
    name: custom-authentication-provider-example
  datasource:
    url: jdbc:h2:mem:customprovider
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  h2:
    console:
      enabled: true
