-- Spring Security ACL schema for H2 (used in MockMvc / unit tests)
CREATE SEQUENCE IF NOT EXISTS acl_sid_sequence START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS acl_class_sequence START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS acl_sid (
    id          BIGINT       NOT NULL DEFAULT nextval('acl_sid_sequence') PRIMARY KEY,
    principal   BOOLEAN      NOT NULL,
    sid         VARCHAR(100) NOT NULL,
    CONSTRAINT uk_acl_sid UNIQUE (sid, principal)
);

CREATE TABLE IF NOT EXISTS acl_class (
    id          BIGINT       NOT NULL DEFAULT nextval('acl_class_sequence') PRIMARY KEY,
    class       VARCHAR(500) NOT NULL,
    CONSTRAINT uk_acl_class UNIQUE (class)
);

CREATE TABLE IF NOT EXISTS acl_object_identity (
    id                  BIGINT  NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_id_class     BIGINT  NOT NULL,
    object_id_identity  VARCHAR(36) NOT NULL,
    parent_object       BIGINT,
    owner_sid           BIGINT,
    entries_inheriting  BOOLEAN NOT NULL,
    CONSTRAINT uk_acl_obj UNIQUE (object_id_class, object_id_identity),
    CONSTRAINT fk_acl_obj_class  FOREIGN KEY (object_id_class)  REFERENCES acl_class(id),
    CONSTRAINT fk_acl_obj_parent FOREIGN KEY (parent_object)    REFERENCES acl_object_identity(id),
    CONSTRAINT fk_acl_obj_owner  FOREIGN KEY (owner_sid)        REFERENCES acl_sid(id)
);

CREATE TABLE IF NOT EXISTS acl_entry (
    id                  BIGINT  NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    acl_object_identity BIGINT  NOT NULL,
    ace_order           INT     NOT NULL,
    sid                 BIGINT  NOT NULL,
    mask                INT     NOT NULL,
    granting            BOOLEAN NOT NULL,
    audit_success       BOOLEAN NOT NULL,
    audit_failure       BOOLEAN NOT NULL,
    CONSTRAINT uk_acl_entry UNIQUE (acl_object_identity, ace_order),
    CONSTRAINT fk_acl_entry_obj FOREIGN KEY (acl_object_identity) REFERENCES acl_object_identity(id),
    CONSTRAINT fk_acl_entry_sid FOREIGN KEY (sid)                 REFERENCES acl_sid(id)
);
