-- Spring Security ACL schema for H2
-- These four tables are the minimum required by JdbcMutableAclService.
-- The exact column names and types must match what BasicLookupStrategy expects.
--
-- DROP statements run first so that @DirtiesContext test restarts begin with
-- a clean ACL state. The in-memory H2 database persists across Spring context
-- restarts (DB_CLOSE_DELAY=-1), so without these drops the ACL tables would
-- accumulate rows from previous test runs and trigger AlreadyExistsException.

DROP TABLE IF EXISTS acl_entry;
DROP TABLE IF EXISTS acl_object_identity;
DROP TABLE IF EXISTS acl_sid;
DROP TABLE IF EXISTS acl_class;

CREATE TABLE IF NOT EXISTS acl_class (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class VARCHAR(255) NOT NULL,
    UNIQUE (class)
);

CREATE TABLE IF NOT EXISTS acl_sid (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    principal BOOLEAN      NOT NULL,
    sid       VARCHAR(255) NOT NULL,
    UNIQUE (sid, principal)
);

CREATE TABLE IF NOT EXISTS acl_object_identity (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_id_class    BIGINT  NOT NULL REFERENCES acl_class (id),
    object_id_identity BIGINT  NOT NULL,
    parent_object      BIGINT  REFERENCES acl_object_identity (id),
    owner_sid          BIGINT  REFERENCES acl_sid (id),
    entries_inheriting BOOLEAN NOT NULL,
    UNIQUE (object_id_class, object_id_identity)
);

CREATE TABLE IF NOT EXISTS acl_entry (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    acl_object_identity BIGINT  NOT NULL REFERENCES acl_object_identity (id),
    ace_order           INT     NOT NULL,
    sid                 BIGINT  NOT NULL REFERENCES acl_sid (id),
    mask                INTEGER NOT NULL,
    granting            BOOLEAN NOT NULL,
    audit_success       BOOLEAN NOT NULL,
    audit_failure       BOOLEAN NOT NULL,
    UNIQUE (acl_object_identity, ace_order)
);
